[colors.primary]
background = "#eaeef1"
foreground = "#525b8f"
dim_foreground = "#818ec9"
bright_foreground = "#525b8f"

[colors.cursor]
text = "#eaeef1"
cursor = "#85bbff"

[colors.vi_mode_cursor]
text = "#eaeef1"
cursor = "#85bbff"

[colors.search.matches]
foreground = "#eaeef1"
background = "#acc2df"

[colors.search.focused_match]
foreground = "#eaeef1"
background = "#acc2df"

[colors.footer_bar]
foreground = "#eaeef1"
background = "#e3e9ed"

[colors.hints.start]
foreground = "#eaeef1"
background = "#d19700"

[colors.hints.end]
foreground = "#eaeef1"
background = "#e3e9ed"

[colors.selection]
text = "#eaeef1"
background = "#85bbff"

[colors.normal]
black = "#eaeef1"
red = "#e153b3"
green = "#9e55dd"
yellow = "#4897e8"
blue = "#4d5de5"
magenta = "#f04f4e"
cyan = "#dd6e96"
white = "#525b8f"

[colors.bright]
black = "#6f78aa"
red = "#e153b3"
green = "#9e55dd"
yellow = "#4897e8"
blue = "#4d5de5"
magenta = "#f04f4e"
cyan = "#dd6e96"
white = "#818ec9"

[[colors.indexed_colors]]
index = 16
color = "#d19700"

[[colors.indexed_colors]]
index = 17
color = "#acc2df"